config/routes.rb
Rails.application.routes.draw do
 

root 'home#dashboard', :via => :get

devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', profile: 'profile'  },
                   controllers: { omniauth_callbacks: "omniauth_callbacks" ,registrations: "registrations"}
                  resources :users, :only =>[:show, :index]
                  match 'users/:id' => 'users#show', via: :get
                  match 'profile/show/:id' => 'profile#show', via: :get  
    
 resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts
  
   match 'posts/:id' =>"posts#show" ,via: :get
  
  resources :comments

 match "static_pages/home" => "static_pages#home", via: [:get, :post]

               

  resources :relationships,only: [:create, :destroy]

resources :friendships
   resources :converzations do
    resources :massages
  end

  resources :conversations do   
   member do
      post :reply
      post :trash
      post :untrash
   end
 end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  
   get 'profile/index' 
   get 'profile/show' 

end

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="Post">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
 <div class="widget-3 widget-last widget widget_polygon_widget" id="polygon_widget-2">
  <ul id="recentcomments">
    <li class="recentcomments"><%= link_to feed_item.user.username, feed_item.user %>
      <br><%= link_to feed_item.content , post_path(feed_item.id) %>
      <% if current_user?(feed_item.user) %>
      <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %> <% end %>
      <div class="palignleft"></div>
      <b> Posted <%= time_ago_in_words(feed_item.created_at) %> ago.</b> </br></br>
    </li>
  </ul>
</div>

app/views/shared/_form.html.erb
<%= form_for @comment do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :post_id, value: @post.id %>

  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit class: 'small button' %>
  </div>
<% end %>

app/views/shared/_intro_page.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div id="carousel-example" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example" data-slide-to="1"></li>
                    <li data-target="#carousel-example" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="http://www.prepbootstrap.com/Content/images/template/carouselstaticheader/slide_03.jpg" alt="First slide" />
                        <div class="carousel-caption">
                            <h3>Welcome to the Social app</h3>
                            <p>
                            The best way of keep in touch with friends.
                            </p>
                            <p><%= link_to "Sign up now!", new_user_registration_path,class: "btn btn-clear btn-sm btn-min-block" %>
                        <%= link_to "login", new_user_session_path,class: "btn btn-clear btn-sm btn-min-block" %></p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="http://www.prepbootstrap.com/Content/images/template/carouselstaticheader/slide_02.jpg" alt="Second slide" />
                        <div class="carousel-caption">
                            <h3>Welcome to the Social app</h3>
                            <p>
                               The best way of keep your smile forever.
                            </p>
                     <p><%= link_to "Sign up now!", new_user_registration_path,class: "btn btn-clear btn-sm btn-min-block" %>
                        <%= link_to "login", new_user_session_path,class: "btn btn-clear btn-sm btn-min-block" %>
                     </p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="http://www.prepbootstrap.com/Content/images/template/carouselstaticheader/slide_01.jpg" alt="Third slide" />
                        <div class="carousel-caption">
                            <h3>Welcome to the Social app</h3>
                            <p>
                               The best way to share your emotions with your friends.
                            </p>
                            <p><%= link_to "Sign up now!", new_user_registration_path,class: "btn btn-clear btn-sm btn-min-block" %>
                        <%= link_to "login", new_user_session_path,class: "btn btn-clear btn-sm btn-min-block" %></p>
                        </div>
                    </div>
                </div>

                <!-- Left and right controls -->
                <a class="left carousel-control" href="#carousel-example" role="button" data-slide="prev">
                    <span class="fa fa-arrow-left" aria-hidden="true"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example" role="button" data-slide="next">
                    <span class="fa fa-arrow-right" aria-hidden="true"></span>
                </a>
            </div>
            <div class="main-text hidden-xs">
                <div class="col-md-12 text-center">
                    <h1>Social Application</h1>
                    <h3>More Friends , More Chat, More Happiness !!
                    </h3>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_navigation_bar.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Social</a>
    </div>
  
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li ><%= link_to 'dashboard' , root_path %></li>
       <li><%= link_to 'Feed', static_pages_home_path%></li>
        <li><%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
        <% end %></li>
       
         <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb))%></li> 
                  <li> <%= link_to user_path(current_user) do %>
                     <span><%= current_user.username %></span>
              <%end%> </li>
          </ul>


      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <form class="navbar-form navbar-right">
          <ul class="nav navbar-nav">
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Settings<span class="caret"></span></a>
                 <ul class="dropdown-menu" role="menu"> 
                     <li >
                      <%= link_to('Edit Profile', edit_user_registration_path) %>
                     </li>
                     <li>
                        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>     
                     </li>
                    </ul>
            </li>
          </ul>
        </form>
    </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>

app/views/shared/_new_post.html.erb
<%= form_for(@post) do |f| %>
 <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field postTextarea">
    <%= f.text_area :content ,placeholder: "Compose new post..." %>
    <%= f.file_field :avatar %>
</div>
<div class="actions post">
  <%= f.submit "post" ,class: "btn btn-large btn-primary" %>
</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
 <% if user_signed_in? %>
<h1>
  <%= current_user.username %>
</h1>
<span>
  <%= link_to "view my profile", '/users/' + current_user.id.to_s %>
</span>
<%end%>