config/routes.rb
Rails.application.routes.draw do
 

root 'home#dashboard', :via => :get

devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', profile: 'profile'  },
                   controllers: { omniauth_callbacks: "omniauth_callbacks" ,registrations: "registrations"}
                  resources :users, :only =>[:show, :index]
                  match 'users/:id' => 'users#show', via: :get
                  match 'profile/show/:id' => 'profile#show', via: :get  
    
 resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts
  
   match 'posts/:id' =>"posts#show" ,via: :get
  
  resources :comments

 match "static_pages/home" => "static_pages#home", via: [:get, :post]

               

  resources :relationships,only: [:create, :destroy]

resources :friendships
   resources :converzations do
    resources :massages
  end

  resources :conversations do   
   member do
      post :reply
      post :trash
      post :untrash
   end
 end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  
   get 'profile/index' 
   get 'profile/show' 

end

app/models/converzation.rb
class Converzation < ActiveRecord::Base
	belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
 
  has_many :massages, dependent: :destroy
 
  validates_uniqueness_of :sender_id, :scope => :recipient_id
 
  scope :involving, -> (user) do
    where("converzations.sender_id =? OR converzations.recipient_id =?",user.id,user.id)
  end
 
  scope :between, -> (sender_id,recipient_id) do
    where("(converzations.sender_id = ? AND converzations.recipient_id =?) OR (converzations.sender_id = ? AND converzations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/controllers/converzations_controller.rb
class ConverzationsController < ApplicationController
	before_filter :authenticate_user!
 
  layout false
  def index
  end
 
  def create
    if Converzation.between(params[:sender_id],params[:recipient_id]).present?
      @converzation = Converzation.between(params[:sender_id],params[:recipient_id]).first
    else
      @converzation = Converzation.create!(converzation_params)
    end
 
    render json: { converzation_id: @converzation.id }
  end
 
  def show
    @converzation = Converzation.find(params[:id])
    @reciever = interlocutor(@converzation)
    @massages = @converzation.massages
    @massage = Massage.new
  end
 
  private
  def converzation_params
    params.permit(:sender_id, :recipient_id)
  end
 
  def interlocutor(converzation)
    current_user == converzation.recipient ? converzation.sender : converzation.recipient
  end
end

app/helpers/converzations_helper.rb
module ConverzationsHelper
end

app/views/converzations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>
 
    <h1><%= @reciever.username %> </h1>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
     
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @converzation.id %> &nbsp; &nbsp;   
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @converzation.id %> 
 
 </div>
  <br clear="all"/>
</div>
 </div>
<div class="chatboxcontent">
  <% if @massages.any? %>
      <%= render @massages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@converzation, @massage], :remote => true, :html => {id: "converzation_form_#{@converzation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @converzation.id %>
  <% end %>
</div>
<%= subscribe_to converzation_path(@converzation) %>